spring:
  datasource:
    database-key-name: legolandserver1-lego-sandbox
  config:
    import: file:${import-path}/database/database-configuration.yml

management:
  endpoints:
    web:
      exposure:
        include: "*"