apiVersion: apps/v1
kind: Deployment
metadata:
  name: lego-data-service-deployment
  namespace: sandbox
  labels:
    app: lego-data-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lego-data-service-deployment
  template:
    metadata:
      name: lego-data-service-deployment
      labels:
        app: lego-data-service-deployment
    spec:
      containers:
        - name: lego-data-service-deployment
          image: quay.io/tvattima/lego-data-service:sandbox
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: ABC
              value: "123"
      restartPolicy: Always
      