name: 'Build Test Deploy'
on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - develop
      - master
    types:
      - closed

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          architecture: x64
          cache: maven

      - name: mvn deploy
        run: mvn --update-snapshots deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  buildah:
    needs: build-test-deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: buildah-build
        id: buildah-build
        uses: redhat-actions/buildah-build@v2
        with:
          image: lego-data-service
          tags: ${{ github.sha }} snapshot latest
          platforms: linux/arm64
          containerfiles: |
            ./kubernetes/Containerfile

  podman:
    needs: buildah
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Podman Push
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.buildah-build.outputs.image }}
          tags: ${{ steps.buildah-build.outputs.tags }}
          registry: quay.io/tvattima
          username: ${{ vars.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

  deploy-to-legolandserver1:
    needs: podman
    runs-on: [ self-hosted, Linux, ARM64 ]

    steps:
      - name: Redeploy on Kubernetes cluster
        run: |
          kubectl set image deployment/lego-data-service-deployment lego-data-service-deployment=quay.io/tvattima/lego-data-service:snapshot --namespace=sandbox