name: 'Build Test Deploy'
on:
  push:
    branches:
      - 'feature/**'
#  pull_request:
#    branches:
#      - develop
#      - master
#    types:
#      - closed

jobs:
  Feature-Branch-Maven-Deploy-Snapshot:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
          cache: maven
      - name: mvn clean deploy
        run: mvn --batch-mode --update-snapshots deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: buildah-build
        id: buildah-build
        uses: redhat-actions/buildah-build@v2
        with:
          image: lego-data-service
          tags: ${{ github.sha }} snapshot latest
          platforms: linux/arm64
          containerfiles: |
            ./kubernetes/Containerfile
      - name: Log in to Quay.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ vars.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
          registry: quay.io/tvattima/lego-data-service

      - name: podman-push
        id: podman-push
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.buildah-build.outputs.image }}
          tags: ${{ steps.buildah-build.outputs.tags }}
          registry: quay.io/tvattima

  deploy-to-legolandserver1:
    needs: Feature-Branch-Maven-Deploy-Snapshot
    runs-on: [ self-hosted, Linux, ARM64 ]

    steps:
      - name: Redeploy on Kubernetes cluster
        run: |
          kubectl set image deployment/lego-data-service-deployment lego-data-service-deployment=quay.io/tvattima/lego-data-service:snapshot --namespace=sandbox