name: 'feature branch mvn deploy snapshot'
on:
  push:
    branches:
      - 'feature/**'
      - 'develop'
jobs:
  Feature-Branch-Maven-Deploy-Snapshot:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        architecture: x64
        cache: maven
    - name: mvn clean install
      run: mvn --batch-mode --update-snapshots deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  Feature-Branch-Image-Build:
    needs: Feature-Branch-Maven-Deploy-Snapshot
    runs-on: ubuntu-latest
    steps:
      - name: Buildah Action
        uses: redhat-actions/buildah-build@v2
        with:
          image: my-new-image
          tags: v1 ${{ github.sha }}
          containerfiles: |
            ./kubernetes/Containerfile
          build-args: |
            some_arg=some_value