name: 'feature branch mvn deploy snapshot'
on:
  push:
    branches:
      - 'feature/**'
      - 'develop'

jobs:
  Feature-Branch-Maven-Deploy-Snapshot:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
          cache: maven
      - name: mvn clean install
        run: mvn --batch-mode --update-snapshots deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: buildah-build
        id: buildah-build
        uses: redhat-actions/buildah-build@v2
        with:
          image: lego-data-service
          tags: ${{ github.sha }} snapshot latest
          containerfiles: |
            ./kubernetes/Containerfile
      - name: Log in to Quay.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ vars.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
          registry: quay.io/tvattima/lego-data-service

      - name: podman-push
        id: podman-push
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.buildah-build.outputs.image }}
          tags: ${{ steps.buildah-build.outputs.tags }}
          registry: quay.io/tvattima

      - name: Print image url
        run: echo "Image pushed to ${{ steps.podman-push.outputs.registry-paths }}"