name: 'feature branch :: image build'
run-name: 'feature branch :: image build'
on:
  workflow_run:
    workflows: ["feature branch :: mvn deploy snapshot"]
    types:
      - completed
jobs:
  Feature-Branch-Image-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Buildah Action
        uses: redhat-actions/buildah-build@v2
        with:
          image: my-new-image
          tags: v1 ${{ github.sha }}
          containerfiles: |
            ./kubernetes/Containerfile
          build-args: |
            some_arg=some_value